# Generated by Django 4.2.13 on 2024-05-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now=True)),
                ('first_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('animals', models.BooleanField(blank=True, null=True)),
                ('amount_guests', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=100, null=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('message', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
