# Generated by Django 4.2.13 on 2024-05-27 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_booking_options_alter_booking_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_item',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='nationality',
            field=models.CharField(),
        ),
    ]
