# Generated by Django 4.2.13 on 2024-06-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(default='Hello street 6', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_item',
            field=models.CharField(choices=[('Upper Apartment', 'Upper Apartment'), ('Lower Apartment', 'Lower Apartment'), ('Whole House', 'Whole House')], default='Upper Apartment', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(blank=True, choices=[('Requested', 'Requested'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(default='Hi!', max_length=4000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nationality',
            field=models.CharField(choices=[('German', 'German'), ('Other', 'Other')], default='German', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='inquiry',
            field=models.TextField(max_length=4000),
        ),
    ]
