# Generated by Django 4.2.13 on 2024-05-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking_booking_item_alter_booking_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_item',
            field=models.CharField(choices=[('Upper Apartment', 'Upper Apartment'), ('Lower Apartment', 'Lower Apartment'), ('Whole House', 'Whole House')]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nationality',
            field=models.CharField(choices=[('German', 'German'), ('Other', 'Other')]),
        ),
    ]
