# Generated by Django 4.2.13 on 2024-07-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_arrival_date_alter_booking_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(default='18/07/20'),
        ),
    ]
