# Generated by Django 4.2.13 on 2024-07-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_booking_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_item',
            field=models.CharField(choices=[('Upper Apartment', 'Upper Apartment'), ('Lower Apartment', 'Lower Apartment'), ('Whole House', 'Whole House')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nationality',
            field=models.CharField(choices=[('German', 'German'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='zip_code',
            field=models.CharField(max_length=100),
        ),
    ]
