# Generated by Django 4.2.13 on 2024-05-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(help_text="Please enter data in the format '2006-10-25'"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(help_text="Please enter data in the format '2006-10-25'"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(help_text="Please enter data in the format '2006-10-25'"),
        ),
    ]
