# Generated by Django 4.2.13 on 2024-05-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_booking_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='Henna', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='last_name',
            field=models.CharField(default='Hamma', max_length=100),
        ),
    ]
