# Generated by Django 4.2.13 on 2024-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_booking_first_name_alter_booking_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(default='Hello street 6', max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount_guests',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], default='1'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_item',
            field=models.CharField(choices=[('Upper Apartment', 'Upper Apartment'), ('Lower Apartment', 'Lower Apartment'), ('Whole House', 'Whole House')], default='Upper Apartment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.CharField(default='Monster City', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=models.CharField(default='Monster Country', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='hello@gmx.de', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.TextField(default='Hi!', max_length=1000),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nationality',
            field=models.CharField(choices=[('German', 'German'), ('Other', 'Other')], default='German'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='passport_number',
            field=models.CharField(blank=True, default='234', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.BigIntegerField(default='123'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='zip_code',
            field=models.CharField(default='12345', max_length=100),
        ),
    ]
