# Generated by Django 4.2.13 on 2024-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_booking_arrival_date_alter_booking_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(help_text="Please enter data in the format '2006-10-25'"),
        ),
    ]
