# Generated by Django 4.2.13 on 2024-05-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_booking_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='arrival_date',
            field=models.DateField(default='2024-10-30', help_text="Please enter data in the format '2006-10-25'"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(default='2006-10-25', help_text="Please enter data in the format '2006-10-25'"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(default='2024-10-31', help_text="Please enter data in the format '2006-10-25'"),
        ),
    ]
