# Generated by Django 4.2.13 on 2024-05-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_booking_arrival_date_alter_booking_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passport_number',
        ),
    ]
