# Generated by Django 4.2.13 on 2024-05-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_booking_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passport_number',
            field=models.CharField(blank=True, default='234', max_length=100, null=True),
        ),
    ]
