# Generated by Django 4.2.13 on 2024-06-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_booking_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-id']},
        ),
    ]
